### ISSUE TITLE
Cannot read property 'state' of undefined at onSave in 07 Form

### ISSUE THREAD

**Issue by qkreltms** [Lemoncode/react-typescript-samples#151]
Error happens when Button from "../../common/components/form"; clicked.
It is because onSave doesn't bound on the constructor in MemberPageContainer class.

**Original code**
https://github.com/Lemoncode/react-typescript-samples/blob/8d0550b7d9e4e2400173a6fe6b6ec6480fab5aae/07%20Form/src/components/member/pageContainer.tsx#L17-L28

```
  constructor(props: any) {
      super(props)

      this.state = {
        member: {
          id: -1,
          login: "",
          avatar_url: ""
        }
      };

      this.onFieldValueChange = this.onFieldValueChange.bind(this);
      //You should include this
      this.onSave = this.onSave.bind(this);
  }
```

**Comment by brauliodiez** [comment]
Hi thanks for opening the issue, just reviewing seems to working fine, the thing is instead of using _bind.this_ I use _fat arrow_ approach to keep the _this_context.

```typescript
  private onSave = () => {
    memberAPI.saveMember(this.state.member)
      .then(() => {
        toastr.success('Member saved.');
        this.props.history.goBack();
      });
  }
```

That works fine on Typescript classes, the reason why there is a mix of _bind.this_ and _fat arrow_ is just versioning, I think it would be a good idea to move everything to fat arrow, if you want to take this issue you are more than welcome.

About data not being saved is because is not really saving (member reads from github api).

If you can provide further information or you want to get involved enhancing the samples that would be of great help, thanks.
