### ISSUE TITLE
MemberAPI should export default new MemberAPI

### ISSUE THREAD

**Issue by tomas-ortega** [Lemoncode/react-typescript-samples#5]
If not you create a new instance, member.id don't increment rigth, and allways it's 20.

`export default new MemberAPI();`

Proposal

```
import MemberEntity from './memberEntity'
import MembersMockData from './memberMockData'
import * as _ from 'lodash'
// Sync mock data API, inspired from:
// https://gist.github.com/coryhouse/fd6232f95f9d601158e4
class MemberAPI {
  private _idSeed : number;
// (...)
}

export default new MemberAPI();
```

Then we you want to use MemberAPI you don't need to make a "new" anymore, just call, e.g.: MemberAPI.SaveChanges(...)

**Comment by josemigallas** [comment]
May I take over of this issue? I was already working on [this issue](https://github.com/Lemoncode/react-typescript-samples/issues/2).

**Comment by brauliodiez** [comment]
We need to fix this issue today (I I think it was closed by mistake) give me a buzz if you think you can have it ready this morning, if not we will jump on that.

**Comment by josemigallas** [comment]
Consider it done. By the way, although this issue is referring the example 07-08, am I right assuming that all examples with a MemberApi usage must be updated?

**Comment by brauliodiez** [comment]
Yes younare right, thanks a lot

Sent from my Windows Phone

-----Mensaje original-----
De: "Jozan" <notifications@github.com>
Enviado: ‎16/‎03/‎2016 10:01
Para: "Lemoncode/react-typescript-samples" <react-typescript-samples@noreply.github.com>
CC: "Braulio Diez" <braulio.diez@gmail.com>
Asunto: Re: [react-typescript-samples] MemberAPI should export default newMemberAPI (#5)

Consider it done. By the way, although this issue is referring the example 07-08, am I right assuming that all examples with a MemberApi usage must be updated?
