### ISSUE TITLE
14 TestComponent - error TS2307: Cannot find module 'redux-mock-store'.

### ISSUE THREAD

**Issue by tutok** [Lemoncode/react-typescript-samples#74]
I think there is a problem with proper typings for that dependency. Did you forget to commit something?

**Comment by brauliodiez** [comment]
Hi Redux-mock-store typings has changed a bit in the last months, they start with a d.ts in the project that had some issues (we created a manual one), then they add it to the package, and finally it has been removed from the project and added as a typings dependency.

We have this fixed in the following repo:

https://github.com/Lemoncode/redux-testing-typescript

@Nasdan can you update sample 14 on this repo? Thanks
